'use client'

/**
 * AIBriefingCard — the coach's morning briefing, generated by the AI.
 *
 * Three design rules:
 *   1. Always answers the same question: "what matters today?"
 *   2. Each bullet ends in a single concrete action.
 *   3. Be transparent when it's a fallback (no API key or parse failure).
 *
 * The briefing is streamed in visually with a shimmer while the AI writes,
 * then reveals bullets with a stagger. Creates the sense of a co-pilot that
 * just finished reading through your roster for you.
 */

import Link from 'next/link'
import clsx from 'clsx'
import { ArrowRight, AlertTriangle, Calendar, CalendarCheck, Info } from 'lucide-react'
import AIOrb from './AIOrb'
import AIThinkingIndicator from './AIThinkingIndicator'
import TypeIn from './TypeIn'

export interface BriefingItem {
  priority: 'now' | 'today' | 'this_week'
  headline: string
  detail: string
  action_href: string
  action_label: string
}

export interface Briefing {
  greeting: string
  summary: string
  items: BriefingItem[]
  generated_at: string
  model: string
  from_fallback: boolean
}

interface Props {
  briefing: Briefing | null
  loading?: boolean
  className?: string
  onRegenerate?: () => void
}

const PRIORITY: Record<BriefingItem['priority'], { label: string; icon: React.ComponentType<any>; cls: string; dot: string }> = {
  now:       { label: 'Now',        icon: AlertTriangle, cls: 'text-red-600 bg-red-50 border-red-200 dark:text-red-400 dark:bg-red-500/10 dark:border-red-500/20',           dot: 'bg-red-500' },
  today:     { label: 'Today',      icon: Calendar,      cls: 'text-brand bg-brand/8 border-brand/20',                                                                        dot: 'bg-brand' },
  this_week: { label: 'This week',  icon: CalendarCheck, cls: 'text-slate-600 bg-slate-50 border-slate-200 dark:text-slate-400 dark:bg-slate-500/10 dark:border-slate-500/20', dot: 'bg-slate-400' },
}

export default function AIBriefingCard({ briefing, loading, className, onRegenerate }: Props) {
  return (
    <section
      className={clsx(
        'rounded-2xl border border-brand/15 bg-gradient-to-br from-brand/[0.07] via-surface to-surface p-5 animate-fade-in-up',
        className,
      )}
    >
      <div className="flex items-start gap-4">
        <AIOrb size="lg" state={loading ? 'thinking' : 'idle'} />
        <div className="flex-1 min-w-0">
          <p className="text-[10px] font-semibold text-brand uppercase tracking-widest">Today&apos;s briefing</p>
          {loading || !briefing ? (
            <div className="mt-1 space-y-2">
              <div className="h-5 w-48 ai-shimmer-bg rounded" />
              <div className="h-3 w-72 ai-shimmer-bg rounded" />
            </div>
          ) : (
            <>
              <h2 className="font-display text-xl font-bold text-cb-text leading-tight mt-1">
                {briefing.greeting}
              </h2>
              <p className="text-sm text-cb-muted mt-1 leading-relaxed">
                <TypeIn text={briefing.summary} speedMs={14} delayMs={220} />
              </p>
            </>
          )}
        </div>

        {onRegenerate && !loading && (
          <button
            onClick={onRegenerate}
            className="text-[11px] font-medium text-brand hover:text-brand-light transition-colors press rounded-md px-2 py-1 border border-brand/20 hover:bg-brand/5"
            title="Regenerate briefing"
          >
            Refresh
          </button>
        )}
      </div>

      {/* Body */}
      <div className="mt-5">
        {loading || !briefing ? (
          <AIThinkingIndicator
            dense
            stages={[
              'Reading your roster signals',
              'Scanning unread messages',
              'Weighing urgency',
              'Writing your briefing',
            ]}
          />
        ) : briefing.items.length === 0 ? (
          <div className="text-sm text-cb-muted italic">Nothing on the plate this morning.</div>
        ) : (
          <ul className="space-y-2.5 stagger-children">
            {briefing.items.map((item, i) => {
              const p = PRIORITY[item.priority]
              const PIcon = p.icon
              return (
                <li
                  key={i}
                  className="group rounded-xl border border-cb-border bg-surface px-4 py-3 card-lift animate-fade-in-up"
                >
                  <div className="flex items-start gap-3">
                    <span className={clsx('mt-1 inline-flex items-center gap-1 text-[10px] font-semibold uppercase tracking-wider rounded-full border px-2 py-0.5 flex-shrink-0', p.cls)}>
                      <PIcon size={10} />
                      {p.label}
                    </span>
                    <div className="flex-1 min-w-0">
                      <p className="text-sm font-semibold text-cb-text leading-snug">{item.headline}</p>
                      <p className="text-xs text-cb-muted mt-1 leading-relaxed">{item.detail}</p>
                    </div>
                    <Link
                      href={item.action_href}
                      className="flex-shrink-0 inline-flex items-center gap-1 text-[11px] font-medium text-brand hover:text-brand-light transition-all press rounded-md px-2 py-1 border border-brand/15 bg-brand/5 group-hover:bg-brand/10"
                    >
                      {item.action_label}
                      <ArrowRight size={11} className="transition-transform group-hover:translate-x-0.5" />
                    </Link>
                  </div>
                </li>
              )
            })}
          </ul>
        )}
      </div>

      {/* Footer — transparency about the source */}
      {briefing && (
        <div className="mt-4 pt-3 border-t border-brand/10 flex items-center gap-2 text-[10px] text-cb-muted/80">
          <Info size={10} />
          <span>
            {briefing.from_fallback
              ? 'Rule-based briefing — AI not configured. '
              : `Generated by ${briefing.model} at ${new Date(briefing.generated_at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}.`}
            <span className="ml-1 opacity-60">Always revisable.</span>
          </span>
        </div>
      )}
    </section>
  )
}
